# Generated by Django 3.2.20 on 2023-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(default='test@ciantest.ie', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_firstname',
            field=models.CharField(default='Ciantest', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_surname',
            field=models.CharField(default='Lanetest', max_length=50),
            preserve_default=False,
        ),
    ]
